[project]
name = "crud-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "psycopg[binary,pool]>=3.2.11",
]
